version: "3.9"
services:
  
  db:
    image: postgres
    restart: always
    container_name: db
    env_file:
      - .env
    ports:
       - "5432:5432"

  # web:
  #   build: ./web
  #   restart: always
  #   container_name: web
  #   command: poetry run python manage.py runserver 0.0.0.0:8000
  #   env_file:
  #     - .env
  #   depends_on:
  #     - db
  #   ports:
  #     - "8000:8000"
