# Generated by Django 5.0 on 2023-12-30 08:23

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contests", "0001_initial"),
        ("problems", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contests",
            name="problems",
            field=models.ManyToManyField(to="problems.problems"),
        ),
    ]
