# Generated by Django 5.0 on 2024-01-02 03:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contests", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contests",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
