# Generated by Django 5.0 on 2023-12-30 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Problems",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("text", models.TextField()),
                ("input_file", models.CharField(max_length=50)),
                ("output_file", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Tests",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("input", models.TextField()),
                ("output", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Solves",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("rust", "Rust"),
                            ("gcc", "GCC"),
                            ("g++", "GPP"),
                            ("clang", "Clang"),
                            ("clang++", "Clang++"),
                            ("python", "Python"),
                            ("fpc", "Free pascal"),
                        ],
                        max_length=30,
                    ),
                ),
                ("code", models.TextField()),
                (
                    "problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="problems.problems",
                    ),
                ),
            ],
        ),
    ]
