# Generated by Django 5.0 on 2024-01-02 03:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("problems", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="problems",
            name="memory_limitation",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="problems",
            name="time_limitation",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="TestVerdicts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "verdict",
                    models.IntegerField(
                        choices=[
                            (0, "Done"),
                            (1, "Wrong answer"),
                            (2, "Time limit"),
                            (3, "Memory limit"),
                            (4, "Compilation error"),
                            (5, "Runtme error"),
                            (6, "Server error"),
                            (7, "Not tested"),
                        ]
                    ),
                ),
                ("compilation_output", models.TextField()),
                ("runtime_outputput", models.TextField()),
                ("used_ram", models.IntegerField()),
                ("used_time", models.IntegerField()),
                (
                    "solve",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="problems.solves",
                    ),
                ),
                (
                    "test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="problems.tests"
                    ),
                ),
            ],
        ),
    ]
